---
- name: Fedora Configuration
  connection: local
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: install important components
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - dnf-plugins-core
        - dnf-utils
        - util-linux-user
        - snapd
        - git

    - name: install nodejs components
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - npm

    - name: Installing neovim
      dnf:
        name: neovim
        state: latest

    - name: Installing python3-neovim
      dnf:
        name: python3-neovim
        state: present

    - name: Installing zsh
      dnf:
        name: zsh
        state: present

    # Docker Installation and Configuration
    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started

    - name: Tool Installation
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - exa
        - bat
        - tmux
        - flatpak
        - ripgre
        - starship

    # install lazy from copr
    - name: Enable and install Lazy git
      shell: |
        sudo dnf copr enable atim/lazygit -y
        sudo dnf install lazygit -y

    - name: Installing other applications
      dnf:
        name: "{{ with_items }}"
        state: present
      with_items:
        - exa
        - bat
        - neofetch
        - ripgrep
