---

- name: PopOS or Ubuntu Configuration
  connection: local
  hosts: localhost
  become: true
  become_user: root
  tasks:
    
  # instead of using the dnf module, use apt module
  - name: install various components
    apt:
      name: 
        - gnome-tweaks
        - gnome-extensions-app
        - snapd
        - util-linux
      state: present
  - name: install Nodejs components        
    apt:
      name:
        - nodejs
        - npm
      state: present

  - name: Install Ansible Community Galaxy
    shell: |
      ansible-galaxy collection install community.general

  # Install neovim lastest version from github https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb
  - name: install neovim
    shell: |
      cd /home/piktonus97m/Downloads
      wget https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb
      sudo apt install ./nvim-linux64.deb
    
  - name: Installing python3-neovim
    apt:
      name: python3-neovim
      state: present
        
  - name: Installing zsh
    apt:
      name: zsh
      state: present
        
  - name: Installing Apps
    apt:
      name:
        - tmux
        - slack
        - telegram-desktop
        - steam - included in Nobara Project
        - exa
        - bat
        - screenkey
        - neofetch
        - gitg
        - virt-manager
        - ripgrep
        - gnome-builder
        - pavucontrol 
      
  - name: Installing Alacritty
    apt:
      name: alacritty
      state: present
  
  - name: Installing Starship
    snap:
      name: starship

  - name: Installing virtualization tools
    dnf:
      name:
        - spice-vdagent 
        - spice-webdavd
      state: present

  - name: Enable Vivaldi Reposity and Installing Vivaldi
    shell: |
      sudo apt -y install wget gnupg2
      wget -qO- https://repo.vivaldi.com/archive/linux_signing_key.pub | sudo apt-key add -
      sudo add-apt-repository 'deb https://repo.vivaldi.com/archive/deb/ stable main' 
      sudo apt update
      sudo apt install vivaldi-stable -y
      apt policy vivaldi-stable
        
  - name: Enable and install Lazy git 
    shell: |
      LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[0-35.]+')
      curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
      sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit
      lazygit --version

  # Installing cargo and rust 

  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust

  - name: Install Visual Studio Code
    shell: |
      wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      sudo apt update
      sudo apt install code -y

  # Download Jetbrains Toolbox tar file, extract it and install it
  - name: Download Jetbrains Toolbox
    get_url:
      url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.25.12999.tar.gz
      dest: /tmp/jetbrains-toolbox.tar.gz
      mode: 0755

  - name: Extract Jetbrains Toolbox
    unarchive:
      src: /tmp/jetbrains-toolbox.tar.gz
      dest: /tmp
      remote_src: yes
  
  - name: Install Jetbrains Toolbox
    shell: |
      cd /tmp/jetbrains-toolbox-1.25.12999
      ./jetbrains-toolbox

  - name: Install the development package group
    shell: |
      sudo apt install \
      build-essential \
      gdb \
      manpages-dev \
      openjdk-8-jdk-headless \
      openjdk-11-jdk-headless \
      maven \
      build-essential \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common \
      apache2-utils \
      make \
      python3-pip \
      dconf-editor \
      libgconf-2-4 -y

  # Install VirtualBox and its dependencies
  - name: Import VirtualBox GPG Key
    shell: |
      wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -

  - name: Add VirtualBox Repository
    shell: |
      echo "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
      sudo apt update
      
  - name: Install VirtualBox
    shell: |
      sudo apt install virtualbox-6.1 -y
      
  - name: Add Vagrant Repository
    shell: |
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update
      sudo apt install vagrant
      
  - name: Install alacritty-themes from npm
    npm:
      name: alacritty-themes
      global: yes
