---
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
  - name: Configure Git username and email
    shell: git config --global user.name "Francisco Sanabria" && git config --global user.email "piktonus97x@hotmail.com"